Repository kubernetes-sigs/kubetest2, pull requests merged in 2020-09, with the labels that each got.

#47 small build fixes
  .go-version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#49 Add an option for overriding the release directory
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#50 Use gcloud beta command group for shared vpc operations
  kubetest2-gke/deployer/network.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 Upgrade to go 1.15.2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 [GKE deployer] Enable building from source
  go.mod
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/options/build.go
  kubetest2-gke/deployer/up.go
  pkg/build/bazel.go
  pkg/build/build.go
  pkg/build/make.go
  pkg/build/release_push_build.go
  pkg/build/stage.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#54 [GKE] Less strict version checking
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/down.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#55 [GKE] Default version latest.
  kubetest2-gke/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#56 Add more reviewers.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#57 Fix firewall rules for multiproject profile
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 Fix a bug in creating private cluster for gke deployer
  kubetest2-gke/deployer/network.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#59 [GKE] Enable Log dumping
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/dumplogs.go
  kubetest2-gke/deployer/options/build.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#53 [Clusterloader2] Implement a clusterloader2 tester
  kubetest2-kind/deployer/deployer.go
  kubetest2-tester-clusterloader2/main.go
  pkg/testers/clusterloader2/cl2.go
  pkg/testers/clusterloader2/suite/suite.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#63 Add --release-channel flag for kubetest2 gke deployer
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#62 Add a unique identifier to kubetest2 runs
  kubetest2-gke/deployer/build.go
  pkg/app/app.go
  pkg/app/cmd.go
  pkg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#64 [GKE] Add functionality to auto-generate cluster names
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/options/up.go
  kubetest2-gke/deployer/up.go
  kubetest2-gke/deployer/up_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
