Repository kubernetes-sigs/kubetest2, pull requests merged in 2020-07, with the labels that each got.

#2 Bootstrap the repo
  .gitignore
  BUILD.bazel
  Makefile
  go.mod
  go.sum
  kubetest2-eks/BUILD.bazel
  kubetest2-eks/main.go
  kubetest2-gce/BUILD.bazel
  kubetest2-gce/deployer/BUILD.bazel
  kubetest2-gce/deployer/build.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/dumplogs.go
  kubetest2-gce/deployer/up.go
  kubetest2-gce/main.go
  kubetest2-gke/BUILD.bazel
  kubetest2-gke/deployer/BUILD.bazel
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/main.go
  kubetest2-kind/BUILD.bazel
  kubetest2-kind/deployer/BUILD.bazel
  kubetest2-kind/deployer/deployer.go
  kubetest2-kind/main.go
  main.go
  pkg/app/BUILD.bazel
  pkg/app/app.go
  pkg/app/cmd.go
  pkg/app/shim/BUILD.bazel
  pkg/app/shim/shim.go
  pkg/app/testers/BUILD.bazel
  pkg/app/testers/standard/BUILD.bazel
  pkg/app/testers/standard/exec/BUILD.bazel
  pkg/app/testers/standard/exec/exec.go
  pkg/app/testers/standard/ginkgo/BUILD.bazel
  pkg/app/testers/standard/ginkgo/ginkgo.go
  pkg/app/testers/standard/ginkgo/kubectl/BUILD.bazel
  pkg/app/testers/standard/ginkgo/kubectl/kubectl.go
  pkg/app/testers/standard/standard.go
  pkg/app/testers/testers.go
  pkg/build/BUILD.bazel
  pkg/exec/BUILD.bazel
  pkg/metadata/BUILD.bazel
  pkg/process/BUILD.bazel
  pkg/process/junitexec.go
  pkg/types/BUILD.bazel
  pkg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3 gke: support acquiring project from boskos
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/down.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  pkg/boskos/boskos.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4 GCE Deployer can be configured with an arbitrary number of nodes
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5 Basic build, up, down CI test script to be run in prow
  kubetest2-gce/ci-tests/buildupdown.sh
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6 Allow setting --node-num and --machine-type for GKE deployer
  kubetest2-gke/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
