Repository kubernetes-sigs/kubetest2, pull requests merged in 2020-10, with the labels that each got.

#65 Add missed copyright headers to the source files
  kubetest2-gke/deployer/options/build.go
  pkg/build/bazel.go
  pkg/build/make.go
  pkg/build/release_push_build.go
  pkg/build/stage.go
  pkg/testers/clusterloader2/cl2.go
  pkg/testers/clusterloader2/suite/suite.go
  pkg/testers/exec/exec.go
  pkg/testers/ginkgo/package.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 Allow specifying the latest version for a release channel
  go.mod
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 Add helper for using exec.CommandContext
  pkg/process/junitexec.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#69 Add kube-root flag to kind deployer
  kubetest2-kind/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
