Repository kubernetes-sigs/kubetest2, pull requests merged in 2020-08, with the labels that each got.

#11 Default artifacts is absolute path and Ginkgo tester expands KUBECONFIG to absolute path
  pkg/app/cmd.go
  pkg/testers/ginkgo/ginkgo.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#18 Removing EKS and bumping dependencies
  go.mod
  go.sum
  kubetest2-eks/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#15 Ginkgo tester automatically acquires the latest test package
  hack/verify/lint.sh
  pkg/testers/ginkgo/ginkgo.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#20 Also print out the usage for the deployer if no args are provided
  pkg/app/cmd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#14 [Proposal] Multi project multi cluster proposal for GKE deployer
  .gitignore
  go.mod
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/network.go
  pkg/exec/exec.go
  pkg/exec/local.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#21 Run a dummy command to make sure volumes are setup correctly.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 port repo to gimme
  .go-version
  Makefile
  hack/build/setup-go.sh
  hack/ci/unit.sh
  hack/go_container.sh
  hack/third_party/gimme/LICENSE
  hack/third_party/gimme/README.md
  hack/third_party/gimme/gimme
  hack/update/gofmt.sh
  hack/update/tidy.sh
  hack/verify/lint.sh
  hack/verify/tidy.sh
  hack/verify/tidy_quiet.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#25 upgrade to go1.15rc2
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#27 Ginkgo tester has flag report-dir set to ARTIFACTS
  pkg/testers/ginkgo/ginkgo.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Fix the logic to verify network configs when boskos is used
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#26 Add flags to GCE deployer to set cache mutation detector, runtime config, create custom network, and enable pod security policy
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#29 Make boskos resource type configurable and GCP SSH key not required
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#30 Ginkgo tester acquires ginkgo binary from release tar
  pkg/testers/ginkgo/ginkgo.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#31 Run test setup in the Up command
  kubetest2-gke/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#32 Inherit output for GCE deployer build step commands
  kubetest2-gce/deployer/build.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#33 upgrade to go1.15
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#34 GCE deployer creates firewall rule allowing nodeport access
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/firewall.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#35 Add hostport firewall rule creation to GCE deployer
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/firewall.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#38 Revert "Add hostport firewall rule creation to GCE deployer"
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/firewall.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#37 Add RawCommand and RawCommandContext functions
  go.mod
  go.sum
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/deployer.go
  pkg/exec/exec.go
  pkg/exec/local.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#36 Fix a few issues for the kubetest2-gke deployer and add chizhg as reviewer
  kubetest2-gke/OWNERS
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/network.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#39 Refactor kubetest2 gke deployer into different source files
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/dumplogs.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#41 Fix checking GCP SSH key logic
  kubetest2-gke/deployer/commandutils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#42 Fix typo
  pkg/app/shim/testers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#40 Enable build caching in ginkgo tester
  kubetest2-gce/deployer/build.go
  kubetest2-gce/deployer/build_test.go
  pkg/build/build.go
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#43 Basic README for GCE deployer and Usage/Installation for top-level README
  README.md
  kubetest2-gce/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#44 Some fixes to kubetest2 GKE deployer
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#46 gke deployer supports creating private cluster
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M
