Repository kubernetes-sigs/kubetest2, pull requests merged in 2020-11, with the labels that each got.

#70 Normalize gke version
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/build_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#71 Update GKE version extraction/normalization
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/build_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 Bump go to 1.15.5
  .go-version
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Stage sources via k/release API (krel)
  go.mod
  go.sum
  kubetest2-gke/deployer/options/build.go
  pkg/build/make.go
  pkg/build/release_push_build.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#73 Fix --private-cluster-master-ip-range arg for multicluster
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/dumplogs.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#74 disable cgo by default
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#75 Fix an 'index out of range' error when creating non-private clusters
  go.mod
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/network_test.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#76 Bump k/release to v0.6.0
  go.mod
  go.sum
  pkg/build/release_push_build.go
Labels: approved, cncf-cla: yes, lgtm, size/S
