Repository kubernetes-sigs/kubetest2, pull requests merged in 2021-04, with the labels that each got.

#126 Ensure destination parent directory exists.
  pkg/fs/fs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#127 Let CI override $USER
  kubetest2-gce/deployer/common.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#131 allow kubetest2 gke accept major.minor cluster version
  kubetest2-gke/deployer/up.go
  kubetest2-gke/deployer/up_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#129 gke deployer supports creating GKE Autopilot clusters
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M
