Repository kubernetes-sigs/kubetest2, pull requests merged in 2021-02, with the labels that each got.

#89 Setup working directory correctly for bazel staging
  .go-version
  hack/verify/shellcheck.sh
  kubetest2-gce/deployer/build.go
  kubetest2-gke/deployer/build.go
  pkg/build/bazel.go
  pkg/build/krel.go
  pkg/build/make.go
  pkg/build/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#90 Refactor to simplify tar extraction logic
  pkg/testers/ginkgo/package.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#92 Add --ginkgo-args flag for additional ginkgo arguments
  pkg/testers/ginkgo/ginkgo.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#93 Add testsuite name in the generated junit-runner.xml file
  pkg/app/app.go
  pkg/metadata/junit.go
  pkg/metadata/writer.go
  pkg/metadata/writer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#91 Refactor artifacts logic
  kubetest2-gce/deployer/deployer.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-kind/deployer/deployer.go
  pkg/app/app.go
  pkg/app/cmd.go
  pkg/artifacts/paths.go
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
  pkg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#95 Extend support for testing from locally built artifacts
  kubetest2-gce/deployer/build.go
  kubetest2-gce/deployer/common.go
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-kind/deployer/build.go
  kubetest2-kind/deployer/deployer.go
  kubetest2-kind/deployer/down.go
  kubetest2-kind/deployer/dumplogs.go
  kubetest2-kind/deployer/up.go
  pkg/app/app.go
  pkg/build/build.go
  pkg/fs/fs.go
  pkg/testers/ginkgo/ginkgo.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#94 [GKE] Add support for gke_make build
  .go-version
  go.mod
  go.sum
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/build/gke_make.go
  kubetest2-gke/deployer/options/build.go
  pkg/build/krel.go
  pkg/build/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#96 [GCE] Use the cluster configuration from config-test.sh
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M
