Repository kubernetes-sigs/kubetest2, pull requests merged in 2021-06, with the labels that each got.

#140 Do not send heartbeat requests to Boskos if the interval is set to 0
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/options/up.go
  pkg/boskos/boskos.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 [kubetest2-gke deployer] Automatically resolves the release channel if it's not specified
  go.mod
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/up.go
  kubetest2-gke/deployer/version.go
  kubetest2-gke/deployer/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#139 kubetest2 gke deployer supports retries with different subnet ranges to avoid conflicts
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/network_test.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#144 Revert "kubetest2 gke deployer supports retries with different subnet…
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/network_test.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#146 Fix to kubetest2 gke deployer supports retries with different subnet ranges to avoid conflicts
  go.mod
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/network_test.go
  kubetest2-gke/deployer/up.go
  kubetest2-gke/deployer/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 set SOURCE_DATE_EPOCH from kubeRepo when building
  pkg/build/bazel.go
  pkg/build/build.go
  pkg/build/make.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#111 Kubetest2 Version Addition
  Makefile
  pkg/app/cmd.go
  pkg/app/shim/shim.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#147 Fix two bugs for kubetest2 gke retry
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#141 Support Windows node pool in kubetest2-gke
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/options/up.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M
