Repository kubernetes-sigs/kubetest2, pull requests merged in 2021-07, with the labels that each got.

#150 Return the error directly if the GKE cluster creation fails in the last retryable region/zone
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#149 Support downloading kubectl for ginkgo tester
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#154 Artifatcs and report-dir update
  pkg/testers/clusterloader2/cl2.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#156 Add a script for running e2e tests for kubetest2 gke deployer
  kubetest2-gke/ci-tests/buildupdown.sh
  kubetest2-gke/ci-tests/test.sh
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#157 Enable Private Google Access for subnets used by private clusters
  kubetest2-gke/deployer/network.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#158 Do not set --workload-pool when creating GKE autopilot clusters
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#159 Implemented the update-latest flag for gke_make
  kubetest2-gke/deployer/build/gke_make.go
  kubetest2-gke/deployer/options/build.go
  pkg/build/krel.go
  pkg/build/options.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
