Repository kubernetes-sigs/kubetest2, pull requests merged in 2021-01, with the labels that each got.

#78 [GCE] use kubectl from PATH instead of get-kube-binaries
  .go-version
  go.mod
  go.sum
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#81 Use Project Number instead of ID for firewall name
  kubetest2-gke/deployer/firewall.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#82 Fix kind deployer build type
  kubetest2-kind/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#83 Expose the ginkgo test package marker as a flag
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#84 Log the commands before running them for easier debugging
  kubetest2-gke/deployer/up.go
  pkg/exec/local.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#86 Avoid two + characters in GKE build version
  kubetest2-gke/deployer/build.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
