Repository kubernetes-sigs/kubetest2, pull requests merged in 2022-06, with the labels that each got.

#183 Decouple RunDir from Artifacts
  pkg/app/app.go
  pkg/app/cmd.go
  pkg/artifacts/paths.go
  pkg/testers/ginkgo/package.go
  pkg/types/types.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#194 Bump klog to klog2
  go.mod
  go.sum
  kubetest2-gce/deployer/build.go
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
  kubetest2-gce/deployer/down.go
  kubetest2-gce/deployer/dumplogs.go
  kubetest2-gce/deployer/firewall.go
  kubetest2-gce/deployer/up.go
  kubetest2-gke/deployer/build.go
  kubetest2-gke/deployer/build/gke_make.go
  kubetest2-gke/deployer/commandutils.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/firewall.go
  kubetest2-gke/deployer/network.go
  kubetest2-gke/deployer/options/build.go
  kubetest2-gke/deployer/up.go
  kubetest2-gke/deployer/utils/util.go
  kubetest2-kind/deployer/build.go
  kubetest2-kind/deployer/deployer.go
  kubetest2-kind/deployer/down.go
  kubetest2-kind/deployer/dumplogs.go
  kubetest2-kind/deployer/up.go
  kubetest2-noop/deployer/deployer.go
  pkg/app/app.go
  pkg/artifacts/paths.go
  pkg/boskos/boskos.go
  pkg/build/bazel.go
  pkg/build/build.go
  pkg/exec/local.go
  pkg/testers/clusterloader2/cl2.go
  pkg/testers/exec/exec.go
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
  pkg/testers/node/node.go
Labels: size/M, cncf-cla: yes, approved, lgtm

#196 Add support for MASTER_SIZE and NODE_SIZE in gce deployer
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
Labels: size/S, cncf-cla: yes, approved, ok-to-test, lgtm

#197 refresh OWNERS
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm
