Repository kubernetes-sigs/kubetest2, pull requests merged in 2022-10, with the labels that each got.

#224 dump cluster logs to artifacts dir instead of run dir
  kubetest2-gce/ci-tests/buildupdown.sh
  kubetest2-gce/deployer/deployer.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-kind/deployer/deployer.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#225 Update OWNERS to include new reviewer
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#195 Add support for an extra nodepool.
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/deployer.go
  kubetest2-gke/deployer/options/cluster.go
  kubetest2-gke/deployer/up.go
  kubetest2-gke/deployer/up_test.go
Labels: cncf-cla: yes, approved, ok-to-test, size/L, lgtm
