Repository kubernetes-sigs/kubetest2, pull requests merged in 2022-07, with the labels that each got.

#199 Bump golang to 1.17
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm

#200 Update ginkgo flags
  pkg/testers/ginkgo/ginkgo.go
Labels: cncf-cla: yes, kind/deprecation, approved, kind/cleanup, size/XS, lgtm

#198 Switch to golang native error wrapping
  go.mod
  pkg/app/app.go
  pkg/app/cmd.go
  pkg/app/shim/deployers.go
  pkg/app/shim/testers.go
  pkg/build/krel.go
Labels: size/M, cncf-cla: yes, approved, lgtm
