Repository kubernetes-sigs/kubetest2, pull requests merged in 2022-01, with the labels that each got.

#177 kubetest2 gke --down releases Boskos projects if they are acquired from Boskos
  kubetest2-gce/deployer/down.go
  kubetest2-gke/deployer/common.go
  kubetest2-gke/deployer/down.go
  kubetest2-gke/deployer/network_test.go
  pkg/boskos/boskos.go
  pkg/testers/node/node.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#178 Add support for NODE_SCOPES and KUBE_GCE_NODE_SERVICE_ACCOUNT
  kubetest2-gce/deployer/common.go
  kubetest2-gce/deployer/deployer.go
Labels: size/S, cncf-cla: yes, approved, ok-to-test, lgtm

#179 emeritus amwat
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm
