Repository kubernetes-sigs/kubetest2, pull requests merged in 2022-09, with the labels that each got.

#219 Update README
  README.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#220 ginkgo: misc non-breaking fixes
  pkg/testers/ginkgo/ginkgo.go
  pkg/testers/ginkgo/package.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#221 place metadata.json in artifacts
  pkg/app/app.go
  pkg/testers/metadata.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#222 fail when no build script can be found
  kubetest2-gke/deployer/options/build.go
Labels: size/S, cncf-cla: yes, approved, lgtm

#223 ensure artifacts dir exists
  pkg/app/app.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
